name: icare
favicon: null
layout_spectrum: 0.5947988361585885
typography_spectrum: 0.7403744629118592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9779886188916862
  lightness: 0.8636093200184405
  saturation: 0.8662632345221937
  rhythmicContrast: 0.34972423897124827
purpose: []
