name: icare
favicon: null
layout_spectrum: 0.5947988361585885
typography_spectrum: 0.25333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#018fd3'
    - '#7fbb53'
    - '#231f21'
    - '#ef3f28'
  brandStrength: 0.5
  lightness: 0.8636093200184405
  saturation: 0.8662632345221937
  rhythmicContrast: 0.34972423897124827
purpose: []
